/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffeemachine1;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ASUS
 */
public class CoffeeMachineFram extends javax.swing.JFrame {
    int minwatercapacity,minbeanscapacity,mincupscapacity,singleespressowater = 0,doubleespressowater = 0,
            singleamericanowater,doubleamericanowater,singlecoffe = 0, doublecoffe = 0,maxwtcapacity = 0;

    /**
     * Creates new form CoffeeMachineFram
     */
    public CoffeeMachineFram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeLabel1 = new javax.swing.JLabel();
        ForEspressoLabel2 = new javax.swing.JLabel();
        ForAmricanoLabel3 = new javax.swing.JLabel();
        RobustaButton = new javax.swing.JButton();
        ArabicaButton2 = new javax.swing.JButton();
        SingleEspressoButton3 = new javax.swing.JButton();
        doubleEspressoButton4 = new javax.swing.JButton();
        SingleAmricanoButton5 = new javax.swing.JButton();
        DoubleAmricanoButton = new javax.swing.JButton();
        StartButton7 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        CaloriesTextField1 = new javax.swing.JTextField();
        CaffienLabel4 = new javax.swing.JLabel();
        CaloriesLabel5 = new javax.swing.JLabel();
        CaffeenTextField1 = new javax.swing.JTextField();
        StartTextField1 = new javax.swing.JTextField();
        endTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typeLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        typeLabel1.setText("Type Of Beans");
        getContentPane().add(typeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 78, -1, -1));

        ForEspressoLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ForEspressoLabel2.setText("For Espresso");
        getContentPane().add(ForEspressoLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 125, -1, -1));

        ForAmricanoLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ForAmricanoLabel3.setText("For Amricano");
        getContentPane().add(ForAmricanoLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 178, -1, -1));

        RobustaButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RobustaButton.setText("Robusta");
        RobustaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RobustaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RobustaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 75, -1, -1));

        ArabicaButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ArabicaButton2.setText("Arabica");
        ArabicaButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArabicaButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(ArabicaButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 75, -1, -1));

        SingleEspressoButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SingleEspressoButton3.setText("Single");
        SingleEspressoButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingleEspressoButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(SingleEspressoButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 122, -1, -1));

        doubleEspressoButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        doubleEspressoButton4.setText("Double");
        doubleEspressoButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleEspressoButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(doubleEspressoButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 122, -1, -1));

        SingleAmricanoButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SingleAmricanoButton5.setText("Single");
        SingleAmricanoButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingleAmricanoButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(SingleAmricanoButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 175, -1, -1));

        DoubleAmricanoButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DoubleAmricanoButton.setText("Double");
        DoubleAmricanoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleAmricanoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DoubleAmricanoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 175, -1, -1));

        StartButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StartButton7.setText("Start");
        StartButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(StartButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 0, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 209, 429, 10));

        CaloriesTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CaloriesTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CaloriesTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaloriesTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(CaloriesTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 290, 91, -1));

        CaffienLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CaffienLabel4.setText("Caffeine");
        getContentPane().add(CaffienLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 252, -1, -1));

        CaloriesLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CaloriesLabel5.setText("Calories");
        getContentPane().add(CaloriesLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        CaffeenTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CaffeenTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CaffeenTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaffeenTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(CaffeenTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 252, 91, -1));

        StartTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        StartTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StartTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(StartTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 210, -1));

        endTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        endTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(endTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 221, 308, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COFEE.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RobustaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RobustaButtonActionPerformed
       
    }//GEN-LAST:event_RobustaButtonActionPerformed

    private void SingleEspressoButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingleEspressoButton3ActionPerformed
         //File logfile = new File("log.txt");
        //FileWriter fileWriter= null;
        
        coffeeMachine cm1 = new coffeeMachine();
        wastTray wt1 = new wastTray();
        wt1.setCapacity(0);
        cm1.setWtray(wt1);
        beansContener bean = new beansContener();
        cm1.setBeans(bean);
        Scanner scan = new Scanner(System.in);
        int p,beans,grind,wtconf;
        double calories, caffiene;
        int i = 0;
//        cm1.setwatercapacity(cm1.getwatercapacity()-singleespressowater);
//                         cm1.setbeanscap(cm1.getbeanscap()-singlecoffe);
//                         cm1.setCups(cm1.getCups()-1);
//                         cm1.getWtray().setCapacity(cm1.getWtray().getCapacity()+1);
                         //if(cm1.getWtray().getCapacity() >= maxwtcapacity){
                            // System.out.println("Your wast tray is full please confirm cleaning it by clicking on any number\n");
                            // wtconf = scan.nextInt();
                         //}
                         CaloriesTextField1.setText("100");
                         CaffeenTextField1.setText("50");
              File logfile = new File("log.txt");
              FileWriter fileWriter= null;
        try {
             fileWriter =new FileWriter(logfile,true);
            fileWriter.write("New single espresso has been served\n");
        } catch (IOException ex) {
            Logger.getLogger(CoffeeMachineFram.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fileWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(CoffeeMachineFram.class.getName()).log(Level.SEVERE, null, ex);
        }
        cm1.setwatercapacity(cm1.getwatercapacity()-singleespressowater);
                         cm1.setbeanscap(cm1.getbeanscap()-singlecoffe);
                         cm1.setCups(cm1.getCups()-1);
                         cm1.getWtray().setCapacity(cm1.getWtray().getCapacity()+1);
               endTextField3.setText("Here is your Single Espresso ,pon Appetit");
    }//GEN-LAST:event_SingleEspressoButton3ActionPerformed

    private void CaloriesTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaloriesTextField1ActionPerformed
        
    }//GEN-LAST:event_CaloriesTextField1ActionPerformed

    private void CaffeenTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaffeenTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaffeenTextField1ActionPerformed

    private void ArabicaButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArabicaButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArabicaButton2ActionPerformed

    private void doubleEspressoButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleEspressoButton4ActionPerformed
        
        coffeeMachine cm1 = new coffeeMachine();
        wastTray wt1 = new wastTray();
        wt1.setCapacity(0);
        cm1.setWtray(wt1);
        beansContener bean = new beansContener();
        cm1.setBeans(bean);
        Scanner scan = new Scanner(System.in);
        int p,beans,grind,wtconf;
        double calories, caffiene;
        int i = 0;
        cm1.setwatercapacity(cm1.getwatercapacity()-doubleespressowater);
                         cm1.setbeanscap(cm1.getbeanscap()-doublecoffe);
                         cm1.setCups(cm1.getCups()-1);
                         cm1.getWtray().setCapacity(cm1.getWtray().getCapacity()+1);
                         //if(cm1.getWtray().getCapacity() >= maxwtcapacity){
                            // System.out.println("Your wast tray is full please confirm cleaning it by clicking on any number\n");
                            // wtconf = scan.nextInt();
                         //}
                          CaloriesTextField1.setText("200");
                          CaffeenTextField1.setText("100");
                        
              File logfile = new File("log.txt");
              FileWriter fileWriter= null;
        try {
             fileWriter =new FileWriter(logfile,true);
            fileWriter.write("New Double espresso has been served\n");
        } catch (IOException ex) {
            Logger.getLogger(CoffeeMachineFram.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fileWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(CoffeeMachineFram.class.getName()).log(Level.SEVERE, null, ex);
        }
        endTextField3.setText("Here is your Double Espresso ,pon Appetit");
    }//GEN-LAST:event_doubleEspressoButton4ActionPerformed

    private void StartTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartTextField1ActionPerformed

    private void SingleAmricanoButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingleAmricanoButton5ActionPerformed
      
        coffeeMachine cm1 = new coffeeMachine();
        wastTray wt1 = new wastTray();
        wt1.setCapacity(0);
        cm1.setWtray(wt1);
        beansContener bean = new beansContener();
        cm1.setBeans(bean);
        Scanner scan = new Scanner(System.in);
        int p,beans,grind,wtconf;
        double calories, caffiene;
        int i = 0;
        cm1.setwatercapacity(cm1.getwatercapacity()-170);
                         cm1.setbeanscap(cm1.getbeanscap()-7);
                         cm1.setCups(cm1.getCups()-1);
                         System.out.println(cm1.getCups());
                         cm1.getWtray().setCapacity(cm1.getWtray().getCapacity()+1);
                         System.out.println(cm1.getWtray().getCapacity());
                         //if(cm1.getWtray().getCapacity() >= maxwtcapacity){
                            // System.out.println("Your wast tray is full please confirm cleaning it by clicking on any number\n");
                            // wtconf = scan.nextInt();
                         //}
                         CaloriesTextField1.setText("60");
                          CaffeenTextField1.setText("35");
                        
              File logfile = new File("log.txt");
              FileWriter fileWriter= null;
        try {
             fileWriter =new FileWriter(logfile,true);
            fileWriter.write("New Single Amricano has been served\n");
        } catch (IOException ex) {
            Logger.getLogger(CoffeeMachineFram.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fileWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(CoffeeMachineFram.class.getName()).log(Level.SEVERE, null, ex);
        }
        endTextField3.setText("Here is your Single Amricano ,pon Appetit");
    }//GEN-LAST:event_SingleAmricanoButton5ActionPerformed

    private void DoubleAmricanoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleAmricanoButtonActionPerformed
      
        coffeeMachine cm1 = new coffeeMachine();
        wastTray wt1 = new wastTray();
        wt1.setCapacity(0);
        cm1.setWtray(wt1);
        beansContener bean = new beansContener();
        cm1.setBeans(bean);
        Scanner scan = new Scanner(System.in);
        int p,beans,grind,wtconf;
        double calories, caffiene;
        int i = 0;
        
//        cm1.setwatercapacity(cm1.getwatercapacity()-220);
//        cm1.setbeanscap(cm1.getbeanscap()-14);
//        cm1.setCups(cm1.getCups()-1);
//        System.out.println(cm1.getCups()+"");
//        cm1.getWtray().setCapacity(cm1.getWtray().getCapacity()+1);
//        System.out.println(cm1.getWtray().getCapacity());
//                         if(cm1.getWtray().getCapacity() >= maxwtcapacity){
//                             System.out.println("Your wast tray is full please confirm cleaning it by clicking on any number\n");
//                             wtconf = scan.nextInt();
//                         }
                          CaloriesTextField1.setText("120");
                          CaffeenTextField1.setText("70");
                         
                        
              File logfile = new File("log.txt");
              FileWriter fileWriter= null;
        try {
             fileWriter =new FileWriter(logfile,true);
            fileWriter.write("New Double Amricano has been served\n");
        } catch (IOException ex) {
            Logger.getLogger(CoffeeMachineFram.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fileWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(CoffeeMachineFram.class.getName()).log(Level.SEVERE, null, ex);
        }
         cm1.setwatercapacity(cm1.getwatercapacity()-220);
        cm1.setbeanscap(cm1.getbeanscap()-14);
        cm1.setCups(cm1.getCups()-1);
        System.out.println(cm1.getCups()+"");
        cm1.getWtray().setCapacity(cm1.getWtray().getCapacity()+1);
        System.out.println(cm1.getWtray().getCapacity());
      endTextField3.setText("Here is your Double Amricano ,pon Appetit");
    }//GEN-LAST:event_DoubleAmricanoButtonActionPerformed

    private void StartButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButton7ActionPerformed
     StartTextField1.setText("Welcome to our Coffee Machine");
    }//GEN-LAST:event_StartButton7ActionPerformed
      
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoffeeMachineFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoffeeMachineFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoffeeMachineFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoffeeMachineFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoffeeMachineFram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArabicaButton2;
    private javax.swing.JTextField CaffeenTextField1;
    private javax.swing.JLabel CaffienLabel4;
    private javax.swing.JLabel CaloriesLabel5;
    private javax.swing.JTextField CaloriesTextField1;
    private javax.swing.JButton DoubleAmricanoButton;
    private javax.swing.JLabel ForAmricanoLabel3;
    private javax.swing.JLabel ForEspressoLabel2;
    private javax.swing.JButton RobustaButton;
    private javax.swing.JButton SingleAmricanoButton5;
    private javax.swing.JButton SingleEspressoButton3;
    private javax.swing.JButton StartButton7;
    private javax.swing.JTextField StartTextField1;
    private javax.swing.JButton doubleEspressoButton4;
    private javax.swing.JTextField endTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel typeLabel1;
    // End of variables declaration//GEN-END:variables

}
